/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2da8e95b-cfd2-41a0-89a3-fdbd49d1082e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_MaXTX0gLW",
    "aws_user_pools_web_client_id": "6jl6dardempvqgoti30fmj8bfd",
    "oauth": {}
};


export default awsmobile;
